In [2]:
from sklearn.datasets import load_digits

In [3]:
digits  = load_digits()

In [4]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [7]:
x = digits['data']

In [8]:
x

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [9]:
y = digits['target']

In [10]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [11]:
x.shape

(1797, 64)

In [12]:
y.shape

(1797,)

In [15]:
list(set(y))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix  , classification_report
from sklearn.linear_model import Perceptron

In [20]:
pd.DataFrame(y).value_counts()

3    183
1    182
5    182
4    181
6    181
9    180
7    179
0    178
2    177
8    174
dtype: int64

In [23]:
pd.DataFrame(y).nunique()

0    10
dtype: int64

In [44]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 41)

In [45]:
pp  = Perceptron()

In [46]:
pp

Perceptron()

In [47]:
pp.fit(x_train , y_train)

Perceptron()

In [48]:
y_train_pred_pp = pp.predict(x_train)

In [49]:
y_train_pred_pp

array([3, 9, 3, ..., 6, 2, 6])

In [50]:
list(set(y_train_pred_pp))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [51]:
accuracy_score(y_train_pred_pp , y_train)

0.9638135003479471

In [52]:
pp.score(x_train , y_train)

0.9638135003479471

In [53]:
y_test_pred_pp = pp.predict(x_test)

In [54]:
y_test_pred_pp

array([9, 0, 3, 9, 1, 2, 1, 6, 6, 7, 6, 5, 7, 6, 6, 1, 2, 9, 8, 7, 4, 0,
       9, 9, 3, 0, 9, 9, 4, 2, 9, 5, 7, 6, 8, 8, 8, 7, 3, 3, 2, 3, 8, 6,
       4, 7, 8, 5, 8, 8, 7, 0, 0, 8, 1, 4, 3, 3, 4, 5, 2, 9, 5, 4, 4, 6,
       6, 5, 0, 2, 8, 8, 7, 3, 2, 3, 5, 9, 9, 4, 0, 3, 5, 5, 9, 2, 9, 9,
       0, 2, 9, 9, 6, 1, 8, 4, 4, 2, 8, 2, 4, 7, 1, 1, 0, 8, 0, 9, 4, 8,
       4, 1, 4, 8, 4, 1, 3, 0, 4, 8, 3, 2, 7, 0, 6, 9, 0, 2, 6, 7, 4, 8,
       7, 5, 0, 2, 2, 2, 9, 7, 1, 8, 4, 7, 6, 2, 9, 2, 3, 9, 6, 1, 1, 5,
       5, 0, 8, 5, 9, 8, 1, 7, 3, 8, 2, 3, 8, 4, 5, 6, 8, 1, 4, 2, 3, 5,
       3, 0, 5, 0, 5, 0, 3, 4, 9, 4, 2, 8, 0, 3, 8, 5, 5, 2, 9, 2, 1, 3,
       5, 0, 4, 5, 3, 5, 6, 6, 0, 8, 0, 4, 9, 6, 6, 2, 8, 4, 3, 5, 2, 7,
       0, 1, 0, 0, 4, 1, 6, 2, 1, 1, 7, 4, 3, 4, 3, 0, 5, 5, 0, 0, 6, 1,
       0, 4, 2, 1, 2, 2, 7, 5, 9, 1, 4, 2, 1, 7, 4, 6, 9, 7, 2, 4, 7, 6,
       8, 8, 7, 9, 3, 1, 7, 6, 7, 9, 6, 4, 6, 2, 0, 1, 8, 2, 6, 6, 5, 8,
       6, 4, 0, 9, 7, 4, 5, 3, 8, 9, 3, 0, 2, 9, 5,

In [55]:
list(set(y_test_pred_pp))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [56]:
accuracy_score(y_test_pred_pp , y_test)

0.9472222222222222

In [57]:
pp.score(x_test , y_test)

0.9472222222222222

In [62]:
print(confusion_matrix(y_train , y_train_pred_pp))

[[139   0   0   0   0   0   0   0   1   0]
 [  0 127   0   2   4   0   1   0  14   1]
 [  0   0 137   0   0   0   0   0   2   0]
 [  0   0   0 142   0   0   0   0   5   0]
 [  0   1   0   0 140   0   0   0   1   0]
 [  0   0   0   2   0 135   0   1   5   0]
 [  0   0   0   0   0   0 145   0   0   0]
 [  0   0   0   0   0   0   0 145   0   1]
 [  0   2   0   0   0   0   0   0 144   0]
 [  0   0   0   2   0   1   0   0   6 131]]


In [63]:
print(confusion_matrix(y_test , y_test_pred_pp))

[[36  0  0  0  1  1  0  0  0  0]
 [ 0 29  0  1  0  0  0  0  3  0]
 [ 0  0 38  0  0  0  0  0  0  0]
 [ 0  0  0 31  0  0  0  0  5  0]
 [ 0  0  0  0 38  0  1  0  0  0]
 [ 0  0  0  0  0 38  0  0  1  0]
 [ 0  0  0  0  0  0 35  0  1  0]
 [ 0  0  0  0  0  0  0 32  1  0]
 [ 0  1  0  1  0  0  0  0 26  0]
 [ 0  0  0  0  0  0  0  1  1 38]]


In [65]:
print(classification_report(y_test_pred_pp , y_test))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97        36
           1       0.88      0.97      0.92        30
           2       1.00      1.00      1.00        38
           3       0.86      0.94      0.90        33
           4       0.97      0.97      0.97        39
           5       0.97      0.97      0.97        39
           6       0.97      0.97      0.97        36
           7       0.97      0.97      0.97        33
           8       0.93      0.68      0.79        38
           9       0.95      1.00      0.97        38

    accuracy                           0.95       360
   macro avg       0.95      0.95      0.94       360
weighted avg       0.95      0.95      0.95       360



### Case Number : 2 Multiple lyare perceptron model on regression problem

In [172]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense
from keras import Sequential

In [173]:
tf.__version__

'2.16.1'

In [174]:
data = pd.read_csv('C:\\Users\\Lenovo\\Downloads\\HousingData.csv')

In [175]:
data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93   0.0  0.573  6.030   NaN  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90    NaN  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99    NaN  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [176]:
data.isnull().sum()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [177]:
data.isnull().any()

CRIM        True
ZN          True
INDUS       True
CHAS        True
NOX        False
RM         False
AGE         True
DIS        False
RAD        False
TAX        False
PTRATIO    False
B          False
LSTAT       True
MEDV       False
dtype: bool

In [178]:
data.isnull().all()

CRIM       False
ZN         False
INDUS      False
CHAS       False
NOX        False
RM         False
AGE        False
DIS        False
RAD        False
TAX        False
PTRATIO    False
B          False
LSTAT      False
MEDV       False
dtype: bool

In [179]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     486 non-null    float64
 1   ZN       486 non-null    float64
 2   INDUS    486 non-null    float64
 3   CHAS     486 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      486 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    486 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB


In [180]:
from sklearn.impute import KNNImputer

In [181]:
knn = KNNImputer()

In [182]:
df = pd.DataFrame(knn.fit_transform(data) , columns = data.columns)

In [183]:
df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [184]:
x = df.iloc[: , :-1]
y = pd.DataFrame(df.iloc[: , -1])

In [185]:
x

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.20  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.90  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.10  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.80  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.20  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...    ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.10  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.70  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.00  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.30  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  78.86  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   7.56  
..       ...     ...    ...  
501     21.0  391.99   9.38  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [186]:
y

MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

In [187]:
from sklearn.preprocessing import StandardScaler

In [188]:
scaler = StandardScaler()

In [189]:
scaled_x = pd.DataFrame(scaler.fit_transform(x) , columns = x.columns)

In [190]:
x_train , x_test , y_train , y_test = train_test_split(scaled_x , y , test_size = 0.25 , random_state = 21)

In [191]:
import tensorflow as tf
from tensorflow import keras 
from keras.layers import Dense
from keras import Sequential
import warnings
warnings.filterwarnings('ignore')

In [192]:
model = Sequential()

In [193]:
len(scaled_x.columns)

13

In [194]:
model.add(layer = Dense(units = 32 , activation = 'relu' , input_dim = len(scaled_x.columns)))
model.add(layer = Dense(units = 16 , activation = 'relu'))
model.add(layer = Dense(units = 1 , activation = 'linear'))
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_17 (Dense)                     │ (None, 32)                  │             448 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_18 (Dense)                     │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_19 (Dense)                     │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 993 (3.88 KB)

 Trainable params: 993 (3.88 KB)

 Non-trainable params: 0 (0.00 B)

In [195]:
model.compile(optimizer = 'adam' , loss = 'mse')

In [196]:
history = model.fit(x_train , y_train , validation_data = (x_test , y_test) , epochs = 100 , batch_size = 32)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 572.6495 - val_loss: 546.3291
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 559.4826 - val_loss: 526.6026
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 577.9571 - val_loss: 505.6358
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 516.4554 - val_loss: 480.3601
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 527.5353 - val_loss: 449.0402
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 464.5529 - val_loss: 412.1547
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 474.1646 - val_loss: 369.0140
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 393.4746 - val_loss: 318.7878
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 336.9651 - val_loss: 261.2856
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 277.0966 - val_loss: 202.8783
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 233.0963 - val_loss: 151.2738
Epoch 12/100
12/12

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12.0418 - val_loss: 15.3728
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.9284 - val_loss: 15.3198
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.1473 - val_loss: 15.2623
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.2335 - val_loss: 15.1533
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.0206 - val_loss: 15.1261
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.7442 - val_loss: 14.9829
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.4319 - val_loss: 14.9523
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.4889 - val_loss: 14.8491
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12.0315 - val_loss: 14.7933
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.7977 - val_loss: 14.8023
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.2417 - val_loss: 14.6978
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8m

In [197]:
y_train_pred = model.predict(x_train)

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step


In [198]:
y_train_pred

array([[30.66723  ],
       [17.380219 ],
       [33.655884 ],
       [26.82393  ],
       [33.666035 ],
       [35.540474 ],
       [13.832254 ],
       [26.568222 ],
       [20.582129 ],
       [33.074444 ],
       [18.170956 ],
       [18.75655  ],
       [16.379519 ],
       [26.053516 ],
       [19.605553 ],
       [ 9.59186  ],
       [44.002342 ],
       [43.869606 ],
       [35.253815 ],
       [16.310974 ],
       [41.642376 ],
       [16.594967 ],
       [26.421646 ],
       [14.157173 ],
       [15.723527 ],
       [23.036774 ],
       [20.034176 ],
       [13.674208 ],
       [17.05845  ],
       [17.89085  ],
       [29.104761 ],
       [10.355851 ],
       [28.29767  ],
       [27.137756 ],
       [16.16915  ],
       [22.17876  ],
       [20.591948 ],
       [26.55702  ],
       [17.924177 ],
       [26.859709 ],
       [25.93875  ],
       [22.741306 ],
       [32.5361   ],
       [20.609741 ],
       [32.809013 ],
       [17.918919 ],
       [19.107334 ],
       [22.02

In [199]:
y_test_pred = model.predict(x_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


In [200]:
y_test_pred

array([[13.977591 ],
       [13.1258135],
       [23.868067 ],
       [42.917297 ],
       [32.45814  ],
       [16.58864  ],
       [23.341007 ],
       [25.913181 ],
       [30.840368 ],
       [15.116064 ],
       [22.289307 ],
       [15.481578 ],
       [25.764288 ],
       [ 8.099479 ],
       [17.337305 ],
       [27.881523 ],
       [13.557395 ],
       [27.55309  ],
       [13.397008 ],
       [16.083641 ],
       [19.598671 ],
       [21.291508 ],
       [16.37296  ],
       [13.0039625],
       [21.332216 ],
       [41.27432  ],
       [24.099699 ],
       [29.494993 ],
       [23.037493 ],
       [25.684391 ],
       [28.187992 ],
       [18.894814 ],
       [30.499722 ],
       [15.42464  ],
       [30.538061 ],
       [32.254715 ],
       [37.409233 ],
       [17.1968   ],
       [21.200195 ],
       [15.217095 ],
       [18.68768  ],
       [35.51031  ],
       [20.54079  ],
       [25.504389 ],
       [23.627214 ],
       [14.045499 ],
       [25.751478 ],
       [21.69

### Client Data

In [201]:
test_data = pd.read_excel('C:\\Users\\Lenovo\\Downloads\\Housing_data_Test.xlsx')

In [202]:
test_data

Unnamed: 0   CRIM  ZN  INDUS  CHAS  NOX  RM  AGE  DIS  RAD  TAX  PTRATIO  \
0           0  0.009  13      3     1  0.9   7   50  3.9    1  325       17   
1           1  0.090  14      5     0  0.8   8   65  6.0    2  400       16   
2           2  0.070  17      6     1  0.7   9   54  8.0    2  400       19   

     B  LSTAT  
0  450      6  
1  430      7  
2  288      8

#### we need to preprocess all things on this new data and data become ready for prediction

In [203]:
test_data = test_data.iloc[: , 1:]

In [204]:
test_data

CRIM  ZN  INDUS  CHAS  NOX  RM  AGE  DIS  RAD  TAX  PTRATIO    B  LSTAT
0  0.009  13      3     1  0.9   7   50  3.9    1  325       17  450      6
1  0.090  14      5     0  0.8   8   65  6.0    2  400       16  430      7
2  0.070  17      6     1  0.7   9   54  8.0    2  400       19  288      8

#### Scaled_data

In [205]:
test_data = pd.DataFrame(scaler.transform(test_data) , columns = scaled_x.columns)

In [206]:
test_data

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0 -0.425130  0.072293 -1.190660  3.702785  2.982858  1.019152 -0.674642   
1 -0.415830  0.115431 -0.898015 -0.280228  2.119025  2.443811 -0.133165   
2 -0.418126  0.244843 -0.751693  3.702785  1.255192  3.868469 -0.530248   

        DIS       RAD       TAX   PTRATIO         B     LSTAT  
0  0.049893 -0.982843 -0.494369 -0.672984  1.023259 -0.941452  
1  1.048169 -0.867883 -0.048923 -1.135347  0.803972 -0.800491  
2  1.998907 -0.867883 -0.048923  0.251741 -0.752967 -0.659530

#### Data is ready for model

In [207]:
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[22.433449],
       [29.131134],
       [26.397247]], dtype=float32)